### ISSUE TITLE
Broken link to the specifications in README.md

### ISSUE THREAD

**Issue by tank666** [googlefonts/gf-glyphs-scripts#58]
[README.md](https://github.com/googlefonts/gf-glyphs-scripts/blob/master/README.md) has a link to a specification that leads to a 404 page. Correct link: [https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist/README.md](https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist/README.md)

**Comment by m4rc1e** [comment]
Thanks. url updated.
